version: "3.7"
x-redis-service: &redis-service
  image: redis:6.2.7-alpine
  restart: always
services:
  # pubsub事件总线
  event_redis:
    <<: *redis-service
    container_name: services-match-event-bus-redis
    ports:
      - 63791:6379
    volumes:
     - ./event_bus_redis/data:/data
     - ./event_bus_redis/conf/redis.conf:/etc/redis/redis.conf
  # 存match#id:userInfo，表示已经加入匹配池
  match_pool_redis:
    <<: *redis-service
    container_name: services-match-match-pool-redis
    ports:
      - 63792:6379
    volumes:
     - ./match_pool_redis/data:/data
     - ./match_pool_redis/conf/redis.conf:/etc/redis/redis.conf
  mysql:
    image: mysql:8
    container_name: services-match-mysql
    ports:
      - 33061:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=servicesMatch
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    restart: always
    privileged: true