// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: rpc_match.proto

package __

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SLaunchByMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2SLaunchByMatch) Reset() {
	*x = C2SLaunchByMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SLaunchByMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SLaunchByMatch) ProtoMessage() {}

func (x *C2SLaunchByMatch) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SLaunchByMatch.ProtoReflect.Descriptor instead.
func (*C2SLaunchByMatch) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{0}
}

type C2SJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *C2SJoin) Reset() {
	*x = C2SJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SJoin) ProtoMessage() {}

func (x *C2SJoin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SJoin.ProtoReflect.Descriptor instead.
func (*C2SJoin) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{1}
}

func (x *C2SJoin) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2SQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *C2SQuit) Reset() {
	*x = C2SQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SQuit) ProtoMessage() {}

func (x *C2SQuit) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SQuit.ProtoReflect.Descriptor instead.
func (*C2SQuit) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{2}
}

func (x *C2SQuit) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type C2SForceQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *C2SForceQuit) Reset() {
	*x = C2SForceQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2SForceQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SForceQuit) ProtoMessage() {}

func (x *C2SForceQuit) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SForceQuit.ProtoReflect.Descriptor instead.
func (*C2SForceQuit) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{3}
}

func (x *C2SForceQuit) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type S2CJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CJoin) Reset() {
	*x = S2CJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CJoin) ProtoMessage() {}

func (x *S2CJoin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CJoin.ProtoReflect.Descriptor instead.
func (*S2CJoin) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{4}
}

type S2CQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CQuit) Reset() {
	*x = S2CQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CQuit) ProtoMessage() {}

func (x *S2CQuit) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CQuit.ProtoReflect.Descriptor instead.
func (*S2CQuit) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{5}
}

type S2CForceQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2CForceQuit) Reset() {
	*x = S2CForceQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CForceQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CForceQuit) ProtoMessage() {}

func (x *S2CForceQuit) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CForceQuit.ProtoReflect.Descriptor instead.
func (*S2CForceQuit) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{6}
}

type S2CLaunchByMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerInfo *ServerInfo `protobuf:"bytes,1,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
}

func (x *S2CLaunchByMatch) Reset() {
	*x = S2CLaunchByMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2CLaunchByMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CLaunchByMatch) ProtoMessage() {}

func (x *S2CLaunchByMatch) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CLaunchByMatch.ProtoReflect.Descriptor instead.
func (*S2CLaunchByMatch) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{7}
}

func (x *S2CLaunchByMatch) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip    string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port  int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_match_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_match_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_rpc_match_proto_rawDescGZIP(), []int{8}
}

func (x *ServerInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ServerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_rpc_match_proto protoreflect.FileDescriptor

var file_rpc_match_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x12, 0x0a, 0x10,
	0x43, 0x32, 0x73, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x42, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x22, 0x22, 0x0a, 0x07, 0x43, 0x32, 0x73, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x07, 0x43, 0x32, 0x73, 0x51, 0x75, 0x69, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0c, 0x43, 0x32, 0x73, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x32, 0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x22, 0x09, 0x0a, 0x07,
	0x53, 0x32, 0x63, 0x51, 0x75, 0x69, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x32, 0x63, 0x46, 0x6f,
	0x72, 0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x22, 0x4a, 0x0a, 0x10, 0x53, 0x32, 0x63, 0x4c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x42, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x36, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x46, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xac, 0x01, 0x0a, 0x05,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x30, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x32, 0x73, 0x4a, 0x6f, 0x69,
	0x6e, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x53, 0x32,
	0x63, 0x4a, 0x6f, 0x69, 0x6e, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74, 0x12,
	0x12, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x32, 0x73, 0x51,
	0x75, 0x69, 0x74, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e,
	0x53, 0x32, 0x63, 0x51, 0x75, 0x69, 0x74, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x09, 0x46, 0x6f, 0x72,
	0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x2e, 0x43, 0x32, 0x73, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x1a,
	0x17, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x53, 0x32, 0x63, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x51, 0x75, 0x69, 0x74, 0x22, 0x00, 0x32, 0x5d, 0x0a, 0x0e, 0x53, 0x61,
	0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0d,
	0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x42, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x32, 0x73, 0x4c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x42, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x53, 0x32, 0x63, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x42, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_match_proto_rawDescOnce sync.Once
	file_rpc_match_proto_rawDescData = file_rpc_match_proto_rawDesc
)

func file_rpc_match_proto_rawDescGZIP() []byte {
	file_rpc_match_proto_rawDescOnce.Do(func() {
		file_rpc_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_match_proto_rawDescData)
	})
	return file_rpc_match_proto_rawDescData
}

var file_rpc_match_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_match_proto_goTypes = []interface{}{
	(*C2SLaunchByMatch)(nil), // 0: rpc_match.C2sLaunchByMatch
	(*C2SJoin)(nil),          // 1: rpc_match.C2sJoin
	(*C2SQuit)(nil),          // 2: rpc_match.C2sQuit
	(*C2SForceQuit)(nil),     // 3: rpc_match.C2sForceQuit
	(*S2CJoin)(nil),          // 4: rpc_match.S2cJoin
	(*S2CQuit)(nil),          // 5: rpc_match.S2cQuit
	(*S2CForceQuit)(nil),     // 6: rpc_match.S2cForceQuit
	(*S2CLaunchByMatch)(nil), // 7: rpc_match.S2cLaunchByMatch
	(*ServerInfo)(nil),       // 8: rpc_match.ServerInfo
}
var file_rpc_match_proto_depIdxs = []int32{
	8, // 0: rpc_match.S2cLaunchByMatch.server_info:type_name -> rpc_match.ServerInfo
	1, // 1: rpc_match.Match.Join:input_type -> rpc_match.C2sJoin
	2, // 2: rpc_match.Match.Quit:input_type -> rpc_match.C2sQuit
	3, // 3: rpc_match.Match.ForceQuit:input_type -> rpc_match.C2sForceQuit
	0, // 4: rpc_match.SandboxService.LaunchByMatch:input_type -> rpc_match.C2sLaunchByMatch
	4, // 5: rpc_match.Match.Join:output_type -> rpc_match.S2cJoin
	5, // 6: rpc_match.Match.Quit:output_type -> rpc_match.S2cQuit
	6, // 7: rpc_match.Match.ForceQuit:output_type -> rpc_match.S2cForceQuit
	7, // 8: rpc_match.SandboxService.LaunchByMatch:output_type -> rpc_match.S2cLaunchByMatch
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_match_proto_init() }
func file_rpc_match_proto_init() {
	if File_rpc_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SLaunchByMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2SForceQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CForceQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2CLaunchByMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_match_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_match_proto_goTypes,
		DependencyIndexes: file_rpc_match_proto_depIdxs,
		MessageInfos:      file_rpc_match_proto_msgTypes,
	}.Build()
	File_rpc_match_proto = out.File
	file_rpc_match_proto_rawDesc = nil
	file_rpc_match_proto_goTypes = nil
	file_rpc_match_proto_depIdxs = nil
}
